### PR TITLE
don't print stacktrace of QueryRejectedException

### PR DESCRIPTION
**Pull request by alexkorotkikh**
Required to avoid spamming logs

### CODE REVIEW

**Comment by pitr** [comment]
:+1:

**Comment by alexkorotkikh** [comment]
👍

**Comment by pitr** [comment]
same on line 507?

**Comment by alexkorotkikh** [comment]
thanks Peter, you're absolutely right

**Comment by pitr** [comment]
:+1:

**Comment by alexkorotkikh** [comment]
👍

**Comment by alexkorotkikh** [comment]
Obsolete because of https://github.com/zalando-zmon/kairosdb/pull/128

**Pull request closed without merging**
