### PR TITLE
fix kairosdb.http.datapoints_requested

### PR DESCRIPTION
**Pull request by alexkorotkikh**
Issue #80 

cc @tfrauenstein

### CODE REVIEW

**Review by vetinari — APPROVED** [review]

**Comment by vetinari** [comment]
:+1:

**Comment by alexkorotkikh** [comment]
:+1:

**Comment by alexkorotkikh** [comment]
@vetinari sorry, need your approval again

**Comment by alexkorotkikh** [comment]
:+1:

**Comment by pitr** [comment]
👍

**Pull request merged**
