### PR TITLE
fix query logging

### PR DESCRIPTION
**Pull request by alexkorotkikh**
fix query type and uuid setting

### CODE REVIEW

**Comment by alex-on-java** [comment]
👍

**Comment by alex-on-java** [comment]
Would it work, if we will set the UUID and the default type in the constructor?
And then override the type in place where we know what is it?

**Comment by alexkorotkikh** [comment]
It would, and I think we will do it as soon as we'll need these values at least in one more place.

**Comment by alexkorotkikh** [comment]
:+1:

**Pull request merged**
