### PR TITLE
 add start and end timestamps to critical_query_finished log

### PR DESCRIPTION
**Pull request by alexkorotkikh**
Issue: #78

### CODE REVIEW

**Comment by pitr** [comment]
could `QueryMetric` be updated to auto-end. I don't actually see where `setEndTime` is called anywhere in the code, except for QueryParser, but it calls it on its own instance of QueryMetric

**Comment by alexkorotkikh** [comment]
@pitr it could be called by reflection while serializing/deserializing. I am a bit afraid to change the behavior about which I don't know why it was created in a first place.

**Comment by pitr** [comment]
this code will be removed at some point too, right? this is for instrumentation?

**Comment by alexkorotkikh** [comment]
at some point, yes

**Comment by pitr** [comment]
👍

**Comment by alexkorotkikh** [comment]
:+1:

**Pull request merged**
