### PR TITLE
Expose JMX metrics through Jolokia agent

### PR DESCRIPTION
**Pull request by vibhory2j**
Creating this pull request to expose following metrics through JMX for monitoring purpose. 

1. /jolokia/read/java.lang:type=Threading/PeakThreadCount/
2. /read/java.lang:type=Threading/ThreadCount/
3. /jolokia/read/java.lang:type=Threading/TotalStartedThreadCount/

Below ones are for Cassandra driver connection pooling.
1. /jolokia/read/cluster1-metrics:name=blocking-executor-queue-depth/Value/
2. /jolokia/read/cluster1-metrics:name=executor-queue-depth/Value/
3. /jolokia/read/cluster1-metrics:name=open-connections/Value/

### CODE REVIEW

**Comment by vibhory2j** [comment]
@mohabusama what do you mean by the label "In Progress"?

**Comment by mohabusama** [comment]
@vibhory2j not sure actually. I think it was added accidentally when I opened the issue on my phone.

**Comment by vibhory2j** [comment]
👍

**Comment by rajatparida86** [comment]
👍

**Pull request merged**
