### PR TITLE
Close the cache file handle

### PR DESCRIPTION
**Pull request by rajatparida86**
Close the cache filehandle in case of exceptions while reading from Cassandra.

### CODE REVIEW

**Comment by alexkorotkikh** [comment]
What was wrong with a `finally` option? Looked more concise to me.

**Comment by rajatparida86** [comment]
@alexkorotkikh with finally, it was complaining about filehandle being closed (null pointer exception), later in the code (https://github.com/zalando-zmon/kairosdb/blob/zalando-kairosdb/src/main/java/org/kairosdb/core/datastore/KairosDatastore.java#L447). 
I mean if no exception occurs while reading from Cassandra, then later that filehandle is closed anyways [here](https://github.com/zalando-zmon/kairosdb/blob/zalando-kairosdb/src/main/java/org/kairosdb/core/http/rest/MetricsResource.java#L471). 
So I only need to handle the filehandle closing in case of an exception

**Comment by alexkorotkikh** [comment]
👍

**Comment by rajatparida86** [comment]
👍

**Pull request merged**
